### ISSUE TITLE
DynamoDb.TransactWriteItems defaults to "*" resource

### ISSUE THREAD

**Issue by OlafConijn** [iann0036/iamfast#5]
when generating an IAM policy for DynamoDb.TransactWriteItems, the permissions (e.g. conditionCheck, putItem, etc) use `*` as resource. would be great if the TableName of TransactWriteItems was used instead

**Comment by iann0036** [comment]
Hey Olaf,

Thanks for raising!

I've fixed the mappings for the TableName here, though it is likely that the implementation will not recognise that not all permissions are needed per usage, so it'll wildcard for those actions.

Let me know if this is indee the case.

**Comment by OlafConijn** [comment]
i created a testcase in the following commit (I didn't want to update my fork just yet)
https://github.com/OlafConijn/iamfast-tests/commit/b1ecd7c26ffb719c3e9d15f88b20611aea306ee3

running the testcase it fails with the following message:
<img width="906" alt="image" src="https://user-images.githubusercontent.com/4547899/180648866-4e193a91-4a5e-4bd9-a853-70d5601941d9.png">
