### ISSUE TITLE
greedy regex sometimes replaces too many parameters in a single resource template

### ISSUE THREAD

**Issue by OlafConijn** [iann0036/iamfast#6]
**update**
- rootcause of the problem is that the regex [here](https://github.com/iann0036/iamfast/blob/5b964f7aa150182f0db01cf237cad5ddc3aeb05a/src/IAMFast.js#L207) matches greedy. multiple `${xxxx} ${yyyy}` expressions get collapsed into 1.
- I believe the regex should be `/\$\{.*?\}/g` instead of `/\$\{.*\}/g`

----------
previous issue (not the rootcause) below

currenlty, execute-api:Invoke permissions use `arn:aws:execute-api:partition:account:*` as resource.
would be great to map the properties of this call into a template:
```
"ApiEndpoint": "abcdef123.execute-api.us-east-1.amazonaws.com",
"Method": "GET",
"Stage": "prod",
"Path": "/path/to/resource",
```_

**Comment by iann0036** [comment]
Awesome catch, thanks!
