### ISSUE TITLE
events:PutTargets,PutRule,etc.etc generate invalid IAM when default EventBus is used

### ISSUE THREAD

**Issue by OlafConijn** [iann0036/iamfast#8]
when generating IAM policies for some of the eventbus operations and not specifying the EventBus (have it use the default bus) the IAM permission is wrong. 

expected: `arn:aws:events:us-east-1:123456789012:rule/MyRule`
actual:  `arn:aws:events:us-east-1:123456789012:rule[/*]/MyRule`

**Comment by iann0036** [comment]
Hey @OlafConijn,

Thanks for raising!

I've added a fix that should hopefully override the SAR-provided ARN with one that should be default EventBus-aware, but try it out and let me know.

**Comment by OlafConijn** [comment]
yes, verified this here: https://github.com/OlafConijn/iamfast-tests/commit/b1ecd7c26ffb719c3e9d15f88b20611aea306ee3#diff-a6fc3e057206a2f8f06c6f0b1bd610600487c74fb270991d81a58bb158a0fdd3
